name = "cloudflare-d1-drizzle-hono"
compatibility_date = "2023-12-01"
node_compat = true

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "firstbucket"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "cloudflare-d1-drizzle-hono"
database_id = "179d351f-4e47-44cf-9400-c8f946374d92"
migrations_dir = "./src/db/migrations"

# [ai]
# binding = "AI"
